site_name: wyr's notes #网站名字
site_url: #你的网址
site_author: wyr #你的名字
theme:
  name: material #主题
  palette:
    primary: deep purple
    accent: purple
markdown_extensions:
  # - pymdownx.arithmatex
  - markdown.extensions.extra