site_name: wyr's notes #网站名字
site_url: https://tsuki0512.github.io/ #你的网址
site_author: wyr #你的名字
theme:
  name: material #主题
  palette:
    primary: deep purple
    accent: purple
  #font:
    #text: LXGW WenKai TC
    #text: PT Sans Caption
  font:
    text: LXGW WenKai Screen GB Screen # Share Tech
    code: JetBrains Mono
  language: zh
  favicon: assets/hzhf.jpg
  logo: assets/hzhf.jpg

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: true
  - markdown.extensions.extra
  - toc:
      permalink: true
  - pymdownx.superfences
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details

nav:
  - Home: index.md
  - 专业课程: 
    - 数据结构基础:
      - 期中前内容: FDS.md
      - 图论: FDS2.md
      - 排序: FDS3.md
    - 图像信息处理: dip历年卷整理.md
    - 数字逻辑设计: 数逻期末.md
    - 高级数据结构与算法分析: ADS_复习整理.md
    - 数据库系统: 
      - cheatingsheet: 数据库系统.md
      - minisql分析.md
    - 计算机体系结构:
      - 概述: 2024_fall/CA/index.md
      - 期末复习: 2024_fall/CA/final_review.md
      - 计算机设计基础: 2024_fall/CA/CA1.md
      - 流水线: 2024_fall/CA/CA2.md
      - 内存层次: 2024_fall/CA/CA3.md
      - 指令级并行: 2024_fall/CA/CA4.md
      - DLP和TLP: 2024_fall/CA/CA5.md
    - 操作系统: 2024_fall/OS/final_review.md
    - 计算理论: 
      - 概述与经验: 2024_fall/计算理论/index.md
      - FA: 2024_fall/计算理论/Lec1.md
      - REX: 2024_fall/计算理论/Lec2.md
    - 计算机网络: 2024_fall/CN/CN.md
    - 编译原理（学习中）: 
      - 期中梳理: 2025_spring/cp/midterm.md
      - Introduction: 2025_spring/cp/chap1.md
      - Lexical Analysis: 2025_spring/cp/chap2.md
      - Parsing: 2025_spring/cp/chap3.md
      - Abstract Syntax: 2025_spring/cp/chap4.md
      - Semantic Analysis: 2025_spring/cp/chap5.md
      - Activation Record: 2025_spring/cp/chap6.md
      - IR Trees: 2025_spring/cp/chap7.md
    - 自然语言处理导论（学习中）:
      - Deep Learning Basics: 2025_spring/nlp/DeepLearningBasics.md
      - Word Embedding: 2025_spring/nlp/WordEmbedding.md
      - Convolutional Neural Networks: 2025_spring/nlp/ConvolutionalNeuralNetworks.md
      - Recurrent Neural Networks: 2025_spring/nlp/RecurrentNeuralNetworks.md
      - Attention: 2025_spring/nlp/Attention.md
      - NLGandNMT: 2025_spring/nlp/NLGAndNMT.md
      - Transformers: 2025_spring/nlp/Transformer.md
    - 数理基础课程资源汇总:
      - 离散数学及其应用: 离散数学.md
      - 微积分（甲）: 微积分.md
      - 大学物理（乙）: 大物.md
      - 线性代数（甲）: 线代.md
      - C程序设计基础: C程.md
  - 论文阅读:
    - 多模态大模型: 2025_spring/多模态/paper笔记.md
  - 课程心得:
    - 通识课: 通识课心得.md
    - 数理基础课: 数理基础课心得.md
    - 专业必修课: 专业必修课心得.md
    - 专业选修课: 专业选修课心得.md
    - 一些碎碎念: 碎碎念.md
  - CMU_DeepVision项目记录: 
    - 概述: CMU_index.md
    - 线上课程: CMU_prelearning.md
    - pytorch入门: pytorch.md
    - Lec1 - Transformers and RAG: CMU_DeepVision_0807.md
    - Lec2 - Ray Tracing: CMU_DeepVision_0807_1.md
    - Lec3 - 3D Vision: CMU_DeepVision_0809.md
    - Lec4 - Deep Learning Basics and Adversarial: CMU_DeepVision_0816.md

repo_url: https://github.com/Tsuki0512/Tsuki0512.github.io
repo_name: Wyr's Notes
extra_css:
- assets/stylesheets.css
- https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
- https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
extra_javascript:
- https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js