site_name: wyr's notes #网站名字
site_url:  #你的网址
site_author: wyr #你的名字
theme:
  name: material #主题
  palette:
    primary: deep purple
    accent: purple
  font:
    text: LXGW WenKai TC
    # text: PT Sans Caption
  language: zh
  favicon: assets/hzhf.jpg
  logo: assets/hzhf.jpg

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.extra
  - toc:
      permalink: true
  - pymdownx.superfences
  - admonition

nav:
  - Home: index.md
  - 专业课程: 
    - 数据结构基础:
      - 期中前内容: FDS.md
      - 图论: FDS2.md
      - 排序: FDS3.md
    - 图像信息处理: dip历年卷整理.md
    - 数字逻辑设计: 数逻期末.md
    - 高级数据结构与算法分析: ADS_复习整理.md
    - 数据库系统: 
      - cheatingsheet: 数据库系统.md
      - minisql分析.md
    - 数理基础课程资源汇总:
      - 离散数学及其应用: 离散数学.md
      - 微积分（甲）: 微积分.md
      - 大学物理（乙）: 大物.md
      - 线性代数（甲）: 线代.md
      - C程序设计基础: C程.md
  - 课程心得:
    - 通识课: 通识课心得.md
    - 数理基础课: 数理基础课心得.md
    - 专业必修课: 专业必修课心得.md
    - 专业选修课: 专业选修课心得.md
    - 一些碎碎念: 碎碎念.md
  - CMU_DeepVision项目记录:
    - 线上课程: CMU_prelearning.md
    - CV自学笔记: CMU_DeepVision.md

repo_url: https://github.com/Tsuki0512/Tsuki0512.github.io
repo_name: Wyr's Notes
extra_css:
  - assets/stylesheets.css